/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import view.TelasUsuario.TelaCadastroUsuario;
import view.TelasOF.TelaCadastroOF;
import view.TelasEstoque.TelaSaidaProduto;
import view.TelasEstoque.TelaCadastroProduto;
import view.TelasEstoque.TelaVisualizaEstoque;
import view.TelasEstoque.TelaRelatorioSaida;
import view.TelasEstoque.TelaEntradaProduto;
import view.TelasOF.TelaAtualizarOF;
import view.TelasOF.TelaPesquisaOFaberto;
import view.TelasOF.TelaPesquisaOFFechado;
import view.TelasClientes.TelaCadastroCliente;
import view.TelasClientes.TelaAtualizarCliente;
import view.TelasClientes.TelaDeletarCliente;
import view.TelasClientes.TelaPesquisaClientes;
import view.TelasEstoque.TelaEqualizador;
import view.TelasEstoque.TelaRelatorioEntrada;
import view.TelasEstoque.TelaVisualizaProdutosEmFalta;
import view.TelasFaturamento.TelaFaturamentoMetalFlex;
import view.TelasFaturamento.TelaFaturamentoFlexMol;
import view.TelasFaturamento.TelaGraficoMF;
import view.TelasFaturamento.TelaGraficoFM;
import view.TelasOF.TelaItensFechados;
import view.TelasRelogio.TelaRelogios;
import view.TelasUsuario.TelaAtualizarUsuario;
import view.qualidade.TelaMedidas;

/**
 *
 * @author gilberto
 */
public class telaPrincipalMDI extends javax.swing.JFrame {
     
    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipalMDI() {
        initComponents();
        this.setExtendedState(telaPrincipalMDI.MAXIMIZED_BOTH);
        setIcon();
        
        
        
                
    }
    
        
    
    
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        user1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_User = new javax.swing.JMenu();
        Menu_User_Cadastrar = new javax.swing.JMenuItem();
        Menu_User_Editar = new javax.swing.JMenuItem();
        Menu_Cliente = new javax.swing.JMenu();
        Menu_Cliente_Cadastrar = new javax.swing.JMenuItem();
        Menu_Cliente_Editar = new javax.swing.JMenuItem();
        Menu_Cliente_Excluir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Menu_Cliente_Pesquisar = new javax.swing.JMenuItem();
        Menu_Pedidos = new javax.swing.JMenu();
        Cadastrar_OF = new javax.swing.JMenuItem();
        Atualizar_OF = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Pedidos_Abertos = new javax.swing.JMenuItem();
        Pedidos_Fechados = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        Menu_Estoque = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        Menu_Semae = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        Menu_Faturamento = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Menu_Equalizador = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        Menu_Qualidade = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Integrado FLEX-MOL & METAL-FLEX    v2.6");

        jDesktopPane1.setLayer(user1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(682, Short.MAX_VALUE)
                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Menu_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        Menu_User.setText("Usuarios");
        Menu_User.setEnabled(false);
        Menu_User.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Menu_User_Cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_User_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        Menu_User_Cadastrar.setText("Cadastrar");
        Menu_User_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_User_CadastrarActionPerformed(evt);
            }
        });
        Menu_User.add(Menu_User_Cadastrar);

        Menu_User_Editar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_User_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        Menu_User_Editar.setText("Editar/Excluir");
        Menu_User_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_User_EditarActionPerformed(evt);
            }
        });
        Menu_User.add(Menu_User_Editar);

        jMenuBar1.add(Menu_User);

        Menu_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        Menu_Cliente.setText("Clientes");
        Menu_Cliente.setEnabled(false);
        Menu_Cliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Menu_Cliente_Cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_Cliente_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_add.png"))); // NOI18N
        Menu_Cliente_Cadastrar.setText("Cadastrar");
        Menu_Cliente_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Cliente_CadastrarActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Menu_Cliente_Cadastrar);

        Menu_Cliente_Editar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_Cliente_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_edit.png"))); // NOI18N
        Menu_Cliente_Editar.setText("Editar");
        Menu_Cliente_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Cliente_EditarActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Menu_Cliente_Editar);

        Menu_Cliente_Excluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_Cliente_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_delete.png"))); // NOI18N
        Menu_Cliente_Excluir.setText("Excluir");
        Menu_Cliente_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Cliente_ExcluirActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Menu_Cliente_Excluir);
        Menu_Cliente.add(jSeparator1);

        Menu_Cliente_Pesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_Cliente_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        Menu_Cliente_Pesquisar.setText("Clientes Cadastrados");
        Menu_Cliente_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Cliente_PesquisarActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Menu_Cliente_Pesquisar);

        jMenuBar1.add(Menu_Cliente);

        Menu_Pedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_text.png"))); // NOI18N
        Menu_Pedidos.setText("Pedidos");
        Menu_Pedidos.setEnabled(false);
        Menu_Pedidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Cadastrar_OF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cadastrar_OF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_add.png"))); // NOI18N
        Cadastrar_OF.setText("Cadastrar/Baixa");
        Cadastrar_OF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_OFActionPerformed(evt);
            }
        });
        Menu_Pedidos.add(Cadastrar_OF);

        Atualizar_OF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Atualizar_OF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_edit.png"))); // NOI18N
        Atualizar_OF.setText("Editar/Excluir");
        Atualizar_OF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atualizar_OFActionPerformed(evt);
            }
        });
        Menu_Pedidos.add(Atualizar_OF);
        Menu_Pedidos.add(jSeparator2);

        Pedidos_Abertos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pedidos_Abertos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        Pedidos_Abertos.setText("Pedidos Abertos");
        Pedidos_Abertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pedidos_AbertosActionPerformed(evt);
            }
        });
        Menu_Pedidos.add(Pedidos_Abertos);

        Pedidos_Fechados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pedidos_Fechados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        Pedidos_Fechados.setText("Pedidos Fechados");
        Pedidos_Fechados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pedidos_FechadosActionPerformed(evt);
            }
        });
        Menu_Pedidos.add(Pedidos_Fechados);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        jMenuItem13.setText("Itens Produzidos no mês");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        Menu_Pedidos.add(jMenuItem13);

        jMenuBar1.add(Menu_Pedidos);

        Menu_Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database.png"))); // NOI18N
        Menu_Estoque.setText("Estoque");
        Menu_Estoque.setEnabled(false);
        Menu_Estoque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database_add.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar Produto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Menu_Estoque.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database_go.png"))); // NOI18N
        jMenuItem2.setText("Entrada de Produto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menu_Estoque.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database_delete.png"))); // NOI18N
        jMenuItem3.setText("Saida de Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Menu_Estoque.add(jMenuItem3);
        Menu_Estoque.add(jSeparator3);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jMenuItem9.setText("Relatorio de Entrada");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Menu_Estoque.add(jMenuItem9);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exclamation.png"))); // NOI18N
        jMenuItem5.setText("Relatorio de Saida");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Menu_Estoque.add(jMenuItem5);
        Menu_Estoque.add(jSeparator5);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        jMenuItem4.setText("Visulizar Estoque");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Menu_Estoque.add(jMenuItem4);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        jMenuItem10.setText("Visualizar Produto Em Falta");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Menu_Estoque.add(jMenuItem10);

        jMenuBar1.add(Menu_Estoque);

        Menu_Semae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock.png"))); // NOI18N
        Menu_Semae.setText("Semae");
        Menu_Semae.setEnabled(false);
        Menu_Semae.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock.png"))); // NOI18N
        jMenuItem6.setText("Relogios");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Menu_Semae.add(jMenuItem6);

        jMenuBar1.add(Menu_Semae);

        Menu_Faturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins.png"))); // NOI18N
        Menu_Faturamento.setText("Faturamento");
        Menu_Faturamento.setEnabled(false);
        Menu_Faturamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_Faturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_FaturamentoActionPerformed(evt);
            }
        });

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins_add.png"))); // NOI18N
        jMenuItem7.setText("Faturamento");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Menu_Faturamento.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chart_bar.png"))); // NOI18N
        jMenuItem8.setText("Gerar Grafico");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Menu_Faturamento.add(jMenuItem8);

        jMenuBar1.add(Menu_Faturamento);

        Menu_Equalizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chart_line.png"))); // NOI18N
        Menu_Equalizador.setText("Equalizador");
        Menu_Equalizador.setEnabled(false);
        Menu_Equalizador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menu_Equalizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_EqualizadorActionPerformed(evt);
            }
        });

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chart_line.png"))); // NOI18N
        jMenuItem11.setText("Equalizador");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Menu_Equalizador.add(jMenuItem11);

        jMenuBar1.add(Menu_Equalizador);

        Menu_Qualidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick.png"))); // NOI18N
        Menu_Qualidade.setText("Qualidade");
        Menu_Qualidade.setEnabled(false);
        Menu_Qualidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        jMenuItem12.setText("Medidas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        Menu_Qualidade.add(jMenuItem12);

        jMenuBar1.add(Menu_Qualidade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_User_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_User_CadastrarActionPerformed
        // TODO add your handling code here:
        TelaCadastroUsuario telaCadUser = new TelaCadastroUsuario();
        jDesktopPane1.add(telaCadUser);
        telaCadUser.setVisible(true);
        
    }//GEN-LAST:event_Menu_User_CadastrarActionPerformed

    private void Menu_Cliente_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Cliente_CadastrarActionPerformed
        TelaCadastroCliente telaCadCliente = new TelaCadastroCliente();
        jDesktopPane1.add(telaCadCliente);
        telaCadCliente.setVisible(true);
    }//GEN-LAST:event_Menu_Cliente_CadastrarActionPerformed

    private void Menu_User_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_User_EditarActionPerformed
        // TODO add your handling code here:
        TelaAtualizarUsuario telaUpdateCliente = new TelaAtualizarUsuario();
        jDesktopPane1.add(telaUpdateCliente);
        telaUpdateCliente.setVisible(true);
    }//GEN-LAST:event_Menu_User_EditarActionPerformed

    private void Menu_Cliente_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Cliente_EditarActionPerformed
        // TODO add your handling code here:
        TelaAtualizarCliente telaUpdateCliente = new TelaAtualizarCliente();
        jDesktopPane1.add(telaUpdateCliente);
        telaUpdateCliente.setVisible(true);
    }//GEN-LAST:event_Menu_Cliente_EditarActionPerformed

    private void Menu_Cliente_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Cliente_PesquisarActionPerformed
        // TODO add your handling code here:
        TelaPesquisaClientes telaFindCliente = new TelaPesquisaClientes();
        jDesktopPane1.add(telaFindCliente);
        telaFindCliente.setVisible(true);
    }//GEN-LAST:event_Menu_Cliente_PesquisarActionPerformed

    private void Menu_Cliente_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Cliente_ExcluirActionPerformed
        // TODO add your handling code here:
        TelaDeletarCliente telaDelCliente = new TelaDeletarCliente();
        jDesktopPane1.add(telaDelCliente);
        telaDelCliente.setVisible(true);
    }//GEN-LAST:event_Menu_Cliente_ExcluirActionPerformed

    private void Cadastrar_OFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_OFActionPerformed
        // TODO add your handling code here:
        TelaCadastroOF telaDeCad = new TelaCadastroOF();
        jDesktopPane1.add(telaDeCad);
        telaDeCad.setVisible(true);
    }//GEN-LAST:event_Cadastrar_OFActionPerformed

    private void Atualizar_OFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atualizar_OFActionPerformed
        // TODO add your handling code here:
        TelaAtualizarOF telaDeATTof = new TelaAtualizarOF();
        jDesktopPane1.add(telaDeATTof);
        telaDeATTof.setVisible(true);
        
    }//GEN-LAST:event_Atualizar_OFActionPerformed

    private void Pedidos_AbertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pedidos_AbertosActionPerformed
        // TODO add your handling code here:
        TelaPesquisaOFaberto telaDeOFaberto = new TelaPesquisaOFaberto();
        jDesktopPane1.add(telaDeOFaberto);
        telaDeOFaberto.setVisible(true);
        
    }//GEN-LAST:event_Pedidos_AbertosActionPerformed

    private void Pedidos_FechadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pedidos_FechadosActionPerformed
        // TODO add your handling code here:
        TelaPesquisaOFFechado telaDeOFfechado = new TelaPesquisaOFFechado();
        jDesktopPane1.add(telaDeOFfechado);
        telaDeOFfechado.setVisible(true);
    }//GEN-LAST:event_Pedidos_FechadosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        TelaVisualizaEstoque tela = new TelaVisualizaEstoque();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaCadastroProduto tela = new TelaCadastroProduto();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TelaEntradaProduto tela = new TelaEntradaProduto();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        TelaSaidaProduto tela = new TelaSaidaProduto();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         TelaRelatorioSaida tela = new TelaRelatorioSaida();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        TelaRelogios tela = new TelaRelogios();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void Menu_FaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_FaturamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_FaturamentoActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        //====REGULA QUAL TELA DE FATURAMENTO VAI SER DA FLEX-MOL OU METAL-FLEX=======
        if(user1.getText().equals("master")||user1.getText().equals("metalflex")){
        TelaFaturamentoMetalFlex tela = new TelaFaturamentoMetalFlex();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        }
        else if(user1.getText().equals("flexmol")){
            TelaFaturamentoFlexMol tela = new TelaFaturamentoFlexMol();
            jDesktopPane1.add(tela);
            tela.setVisible(true);
        }
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        System.out.println("user:"+user1.getText());
        if(user1.getText().equals("metalflex")||user1.getText().equals("master")){
        TelaGraficoMF tela = new TelaGraficoMF();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        }
        else if(user1.getText().equals("flexmol")){
        TelaGraficoFM tela = new TelaGraficoFM();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        TelaRelatorioEntrada tela = new TelaRelatorioEntrada();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        TelaVisualizaProdutosEmFalta tela = new TelaVisualizaProdutosEmFalta();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void Menu_EqualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_EqualizadorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Menu_EqualizadorActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        TelaEqualizador tela = new TelaEqualizador();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        TelaMedidas tela = new TelaMedidas();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        TelaItensFechados tela = new TelaItensFechados();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipalMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem Atualizar_OF;
    public static javax.swing.JMenuItem Cadastrar_OF;
    public static javax.swing.JMenu Menu_Cliente;
    private javax.swing.JMenuItem Menu_Cliente_Cadastrar;
    private javax.swing.JMenuItem Menu_Cliente_Editar;
    private javax.swing.JMenuItem Menu_Cliente_Excluir;
    private javax.swing.JMenuItem Menu_Cliente_Pesquisar;
    public static javax.swing.JMenu Menu_Equalizador;
    public static javax.swing.JMenu Menu_Estoque;
    public static javax.swing.JMenu Menu_Faturamento;
    public static javax.swing.JMenu Menu_Pedidos;
    public static javax.swing.JMenu Menu_Qualidade;
    public static javax.swing.JMenu Menu_Semae;
    public static javax.swing.JMenu Menu_User;
    private javax.swing.JMenuItem Menu_User_Cadastrar;
    private javax.swing.JMenuItem Menu_User_Editar;
    public static javax.swing.JMenuItem Pedidos_Abertos;
    public static javax.swing.JMenuItem Pedidos_Fechados;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenuItem jMenuItem10;
    public static javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    public static javax.swing.JMenuItem jMenuItem6;
    public static javax.swing.JMenuItem jMenuItem7;
    public static javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    public static javax.swing.JLabel user1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/cup.png")));
    }
}
