/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.TelasUsuario;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.bean.Usuario;
import model.dao.UsuarioDAO;

/**
 *
 * @author gilberto
 */
public class TelaAtualizarUsuario extends javax.swing.JInternalFrame {
    private int ID_usuario;
    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaAtualizarUsuario() {
        initComponents();
        UsuarioDAO udao = new UsuarioDAO();
        
        for(Usuario u: udao.find()){
            cmb_nome.addItem(u);
        }
        //====== COR NOS BOTOES=========
        Color VERMELHO = new Color(246, 165, 182);
        Color AZUL = new Color(180, 194, 240);
        Color VERDE = new Color(180, 240, 206);
       
        btn_excluir.setBackground(VERMELHO);
        btn_atualizar.setBackground(AZUL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        txt_senha_conf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btn_atualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmb_nome = new javax.swing.JComboBox<>();
        cmb_perfil = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btn_excluir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Atualizar Cadastro de Usuario");
        setToolTipText("");

        jLabel1.setText("Novo Nome de Usuario:");

        jLabel2.setText("Nova Senha:");

        jLabel3.setText("Confirmar Senha:");

        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thumbnail_METALFLEX (fundo branco).png"))); // NOI18N

        btn_atualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome de Usuario:");

        cmb_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_nomeActionPerformed(evt);
            }
        });

        cmb_perfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gerente", "secretaria", "compras", "qualidade", "almoxarifado" }));
        cmb_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_perfilActionPerformed(evt);
            }
        });

        jLabel6.setText("Prioridade:");

        btn_excluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txt_user)
                            .addComponent(txt_senha)
                            .addComponent(txt_senha_conf, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cmb_nome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(cmb_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_senha_conf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atualizar)
                    .addComponent(btn_excluir)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        // TODO add your handling code here:
        String senha1,senha2;
        senha1=txt_senha.getText();
        senha2=txt_senha_conf.getText();
        
        if(txt_user.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Campo USUARIO em branco!","ERRO AO ATUALIZAR",JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(senha1.equals(senha2)){
                Usuario u = new Usuario();
                UsuarioDAO udao = new UsuarioDAO();
                
                u.setLogin(txt_user.getText());
                u.setSenha(txt_senha.getText());
                u.setPerfil(cmb_perfil.getSelectedItem().toString());
                u.setId_usuario(ID_usuario);
                udao.update(u);
                
                
            }else{
                JOptionPane.showMessageDialog(null,"Senhas Diferentes!","ERRO AO ATUALIZAR",JOptionPane.ERROR_MESSAGE);
                System.out.println(txt_senha.getText()+" ");
                System.out.println(txt_senha_conf.getText());
            }
        }
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void cmb_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_nomeActionPerformed
        // TODO add your handling code here:
        
        Usuario u = (Usuario) cmb_nome.getSelectedItem();
        txt_user.setText(u.getLogin());
        txt_senha.setText(u.getSenha());
        cmb_perfil.setSelectedItem(u.getPerfil());
        ID_usuario=u.getId_usuario();
        
        
    }//GEN-LAST:event_cmb_nomeActionPerformed

    private void cmb_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_perfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_perfilActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        Usuario u = (Usuario) cmb_nome.getSelectedItem();
        UsuarioDAO uDAO = new UsuarioDAO();
        uDAO.delete(u);
        txt_user.setText("");
        txt_senha.setText("");
        txt_senha_conf.setText("");
    }//GEN-LAST:event_btn_excluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JComboBox<Object> cmb_nome;
    private javax.swing.JComboBox<String> cmb_perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JPasswordField txt_senha_conf;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
